Update w.glossary.md
team-monite/api-docs pull request #13
Opened 2021-11-18 13:23 UTC by Babazyga

Added a list of terms related to the "Workflows"

2021-11-18 13:31 UTC, Babazyga commented
@billy-the-fish can you please check it

2021-11-19 09:44 UTC, billy-the-fish requested changes
Nearly there, just a couple of updates. 

Global rule. In a glossary an mention of another term in the glossary must be a link to that term.

2021-11-19 09:44 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - A single set of Rules and Conditions that was dedicated for user-defined purpose.
A single set of [rules](#rule) and [conditions](#condition) dedicated for a user-defined purpose.  
The following terms are synonyms: [workflow](#<link>), [approval flow](#<link>), [spending policy](#<link>).

2021-11-19 09:44 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - A setting that determines the situation for which an Approval policy should be applied.
A setting that determines the situation in which an [approval policy](@approval-policy) is applied.

2021-11-19 09:44 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - A setting that defines what users should approve a submitted payable document in a set range of amounts.
... defines the users who have the rights to approve a submitted payable that contains figures in a specific range.

2021-11-19 09:44 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - An authority of user in the Approval policy.
I don't understand what you mean by authority.

in the [approval policy](#approval-policy)

2021-11-22 10:41 UTC, Babazyga commented on docs/w.glossary.md
> +  - A single set of Rules and Conditions that was dedicated for user-defined purpose.
Sorry, but how can I add a link on it?

2021-11-22 10:48 UTC, Babazyga commented on docs/w.glossary.md
> +  - An authority of user in the Approval policy.
Yep, here I tried to say that "approval permissions" is a kind of "role". 

- For example, in Monite you are an admin
- But in "approval permissions" you are a "team owner"
- And if someone created a rule related to your team that goes like "If an amount more than 500 USD then it should be approved by team owner" then you should review all of the $500+ bills

Does it make sense?

2021-11-22 10:48 UTC, Babazyga commented on docs/w.glossary.md
> +  - A setting that defines what users should approve a submitted payable document in a set range of amounts.
Thanks!

2021-11-22 12:51 UTC, Babazyga commented
@billy-the-fish 
Iain, please check the changes then you'll have time

2021-11-24 09:29 UTC, billy-the-fish requested changes

2021-11-24 09:29 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - A single set of [Rules](@rule) and [Conditions](@condition) that was dedicated for user-defined purpose.
Links in markdowns are denoted with # not @.
Please, always use the present tense

 A single set of [Rules](#rule) and [Conditions](#condition) that determines the payables that users with a specific role may approve.

2021-11-24 09:29 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - A setting that determines the situation for which an [Approval policy](@approval policy) should be applied.
when an [Approval policy](#approval-policy) is applied.

2021-11-24 09:29 UTC, billy-the-fish commented on docs/w.glossary.md
> +  - Rights of the user to validate [payables](@payable) entered into the system.
[payables](#payable)

2021-11-25 10:20 UTC, Babazyga commented
@billy-the-fish 

Thanks, Iain, please check the new set of fixes.

P.S. Maybe you know, why the link didn't apply to the "Approval policies" text?

2021-11-25 17:49 UTC, merged