Mvp13 2
team-monite/api-docs pull request #16
Opened 2021-11-25 06:53 UTC by YuriKirilin

Updated Payable-Management: added curl examples and responses, updated state-machine diagram

2021-11-25 18:46 UTC, billy-the-fish requested changes
Good information in the doc. 

I thought it would be faster to do a few edits. Can you have a quick glance over my changes please.

2021-11-25 20:28 UTC, YuriKirilin commented on docs/g.payable-management.md
> +    curl --location --request POST 'https://api.dev.monite.dev/partner-api/api_users/v1/entities/au-your0000-part-ner0-leve-access0token/access' \
No, URL parameter must be {entity_id} (something like c0f6bbfb-0695-45a6-8cba-759ad35a051a) rather than a partner level token au-your0000-part-ner0-leve-access0token

2021-11-25 20:39 UTC, YuriKirilin commented on docs/g.payable-management.md
> +For example, a member from the Finance team in an entity wants to view all the uploads for record keeping. However, this person has restricted access.
Here is a good place to put a hyperlink link dedicated to role-based access control.
But the RBAC development is not completed yet (as far as I know). Neither do we have such a page.

2021-11-25 20:45 UTC, YuriKirilin commented on docs/g.payable-management.md
> +- **Delete a payable** - Monite enables financial team members to remove or delete a bill from the system. The entity can delete any specific upload. This marks the bill as archived in the system.
As we found out today, support of deletion operation is not done yet. So we don't know what really happens on deletion.  Whether the bill is just marked as archived/deleted, or its record is really removed out of DB.
We shall have to return to this paragraph when the development is completed.

2021-11-25 20:50 UTC, YuriKirilin commented on docs/g.payable-management.md
> +Currently, partial payments are not supported.
I'd rather have this clarification about partial payments near the Pay operation description rather than in Reference section.

2021-11-25 20:50 UTC, YuriKirilin commented on docs/g.payable-management.md
> +    curl --location --request POST 'https://api.dev.monite.dev/partner-api/api_users/v1/entities/au-your0000-part-ner0-leve-access0token/access' \
No, This URL parameter must be {entity_id} (something like c0f6bbfb-0695-45a6-8cba-759ad35a051a) rather than a partner level token au-your0000-part-ner0-leve-access0token

2021-11-25 20:50 UTC, YuriKirilin commented on docs/g.payable-management.md
> +For example, a member from the Finance team in an entity wants to view all the uploads for record keeping. However, this person has restricted access.
Here is a good place to put a hyperlink link to the documentation page describing role-based access control.
But the RBAC development is not completed yet (as far as I know). Neither do we have such a page.

2021-11-25 20:50 UTC, YuriKirilin commented on docs/g.payable-management.md
> +- **Delete a payable** - Monite enables financial team members to remove or delete a bill from the system. The entity can delete any specific upload. This marks the bill as archived in the system.
As we found out today, support of deletion operation is not done yet. So we don't know what really happens on deletion. Whether the bill is just marked as archived/deleted, or its record is really removed out of DB.
We shall have to return to this paragraph when the development is completed.

2021-11-25 21:07 UTC, YuriKirilin commented
> Good information in the doc.
> 
> I thought it would be faster to do a few edits. Can you have a quick glance over my changes please.

I went over your changes and made several comments in a new review. Please, look
Now, as we both have comments on each other changes,  I don't understand clearly, who (you or I) should resolve the conversations and merge the branch. I could do that.

2021-11-26 08:51 UTC, billy-the-fish commented on docs/g.payable-management.md
> +Currently, partial payments are not supported.
In a normal world this sort of information would live in release notes. I don't like having restrictions in the main docs at all. This is why I put it in the reference section.

2021-11-26 08:51 UTC, billy-the-fish commented on docs/g.payable-management.md
> +    curl --location --request POST 'https://api.dev.monite.dev/partner-api/api_users/v1/entities/au-your0000-part-ner0-leve-access0token/access' \
Nice spot. Updated.

2021-11-26 08:52 UTC, billy-the-fish commented on docs/g.payable-management.md
> +For example, a member from the Finance team in an entity wants to view all the uploads for record keeping. However, this person has restricted access.
:-D. Soon as we have it we will add the link :-D

2021-11-26 08:52 UTC, billy-the-fish commented on docs/g.payable-management.md
> +- **Delete a payable** - Monite enables financial team members to remove or delete a bill from the system. The entity can delete any specific upload. This marks the bill as archived in the system.
Removed.

2021-11-26 08:52 UTC, billy-the-fish commented
Good to go for me.

2021-11-26 09:32 UTC, merged